import { MenuItem } from './types';

export const APP_NAME = "DineFlow AI";

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'Spicy Noodle Chicken',
    description: 'Spicy stir-fried noodles with tender chicken breast and fresh vegetables.',
    price: 20.50,
    category: 'Entrees',
    image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=800&q=80',
    calories: 520,
    protein: '54g',
    fats: '36g',
    carbs: '15g',
    sugar: '2g',
    ingredients: ['Dried spaghetti', 'Chicken breast', 'Yellow onion', 'Green garlic', 'Olive oil', 'Red pepper', 'Broccoli'],
    allergens: ['Gluten', 'Soy'],
    isSpicy: true,
    isPopular: true
  },
  {
    id: '2',
    name: 'Delightful Caesar Salad',
    description: 'Fresh romaine lettuce with parmesan cheese, croutons, and caesar dressing.',
    price: 15.50,
    category: 'Entrees',
    image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=800&q=80',
    calories: 320,
    protein: '12g',
    fats: '18g',
    carbs: '10g',
    sugar: '4g',
    ingredients: ['Romaine lettuce', 'Parmesan cheese', 'Croutons', 'Caesar dressing', 'Black pepper'],
    allergens: ['Dairy', 'Gluten', 'Eggs'],
    isVegetarian: true
  },
  {
    id: '3',
    name: 'Chicken Wrap',
    description: 'Grilled chicken wrap with fresh lettuce, tomatoes and creamy sauce.',
    price: 10.50,
    category: 'Grab & Go',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&q=80',
    calories: 450,
    protein: '28g',
    fats: '15g',
    carbs: '40g',
    sugar: '3g',
    ingredients: ['Tortilla wrap', 'Grilled chicken', 'Lettuce', 'Tomato', 'Mayonnaise'],
    allergens: ['Gluten', 'Eggs'],
    isPopular: true
  },
  {
    id: '4',
    name: 'Delightful Bound Salad',
    description: 'A protein-packed salad with chickpeas, chicken, and fresh greens.',
    price: 15.50,
    category: 'Entrees',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    calories: 380,
    protein: '25g',
    fats: '12g',
    carbs: '22g',
    sugar: '5g',
    ingredients: ['Chickpeas', 'Grilled chicken', 'Spinach', 'Cucumber', 'Vinaigrette'],
    allergens: []
  },
  {
    id: '5',
    name: 'Beef Steak Rice Bowl',
    description: 'Tender beef steak slices served over steamed white rice and broccoli.',
    price: 18.50,
    category: 'Entrees',
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
    calories: 650,
    protein: '45g',
    fats: '28g',
    carbs: '55g',
    sugar: '4g',
    ingredients: ['Beef steak', 'White rice', 'Broccoli', 'Soy sauce', 'Garlic'],
    allergens: ['Soy'],
    isPopular: true
  },
  {
    id: '6',
    name: 'Veggie Stir Fry',
    description: 'Mixed seasonal vegetables stir-fried in a light savory sauce.',
    price: 12.50,
    category: 'Entrees',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80',
    calories: 280,
    protein: '8g',
    fats: '10g',
    carbs: '35g',
    sugar: '6g',
    ingredients: ['Broccoli', 'Carrots', 'Snap peas', 'Bell peppers', 'Soy sauce'],
    allergens: ['Soy'],
    isVegetarian: true
  },
  {
    id: '7',
    name: 'Cola Zero',
    description: 'Refreshing sugar-free cola beverage.',
    price: 2.50,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&q=80',
    calories: 0,
    protein: '0g',
    fats: '0g',
    carbs: '0g',
    sugar: '0g',
    ingredients: ['Carbonated water', 'Caramel color', 'Aspartame'],
    allergens: []
  },
  {
    id: '8',
    name: 'Fresh Orange Juice',
    description: 'Freshly squeezed orange juice.',
    price: 5.00,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=800&q=80',
    calories: 110,
    protein: '2g',
    fats: '0g',
    carbs: '26g',
    sugar: '20g',
    ingredients: ['Oranges'],
    allergens: [],
    isVegetarian: true
  },
  {
    id: '9',
    name: 'Chocolate Chip Cookie',
    description: 'Chewy chocolate chip cookie.',
    price: 3.50,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1499636138143-bd649043ea29?w=800&q=80',
    calories: 250,
    protein: '3g',
    fats: '12g',
    carbs: '30g',
    sugar: '18g',
    ingredients: ['Flour', 'Sugar', 'Butter', 'Chocolate chips', 'Eggs'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    isVegetarian: true
  }
];